development:
  adapter: mysql
  encoding: utf8
  database: secret_santa #following rails db naming convention
  username: root
  password: 
  host: localhost

  # Mysql Settings
  # adapter: mysql
  # encoding: utf8
  # database: bort_development
  # username: root
  # password:
  # pool: 5
  
test:
  # Sqlite Settings
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

  # Mysql Settings
  # adapter: mysql
  # encoding: utf8
  # database: bort_test
  # username: root
  # password:
  # pool: 5
  
staging:
  # Sqlite Settings
  adapter: sqlite3
  database: db/staging.sqlite3
  pool: 5
  timeout: 5000

  # Mysql Settings
  # adapter: mysql
  # encoding: utf8
  # database: bort_staging
  # username: root
  # password:
  # pool: 5
  
production:
    adapter: mysql
    encoding: utf8
    database: secret_santa_production #following rails db naming convention
    username: hutch
    password: striker7
    host: db.johnhutch.com
    port: 3306  #not necessary since its the standard mysql port


  # Mysql Settings
  # adapter: mysql
  # encoding: utf8
  # database: bort_production
  # username: root
  # password:
  # pool: 5