development: &non_production_settings
  site_url: http://secret_santa.local
  site_name: Secret Santa
  admin_email: johnhutch@gmail.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://santa_staging.johnhutch.com
  site_name: Secret Santa
  admin_email: johnhutch@gmail.com
  
production:
  site_url: http://santa.johnhutch.com
  site_name: Secret Santa
  admin_email: johnhutch@gmail.com
